### ISSUE TITLE
Problem with using AzureAD as Login Provider

### ISSUE THREAD

**Issue by saigkill** [EdiWang/Moonglade#712] opened 2023-02-09 20:30 UTC
I just have a little question. I have configured AzureAD as described in the docs. The Tenant and ClientIDs are set correctly. Inide AD i configured /signin-oidc for https://saschamanns.de and localhost.

Currently i'm getting: 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/75621/217929753-a396bdfa-c0d7-42c9-bfef-7cf01de2d6a6.png">

So i try to debug this. Should /signin-oidc accessable with a browser, or is it just a available via API-Request?

**Comment by EdiWang** [comment] 2023-02-15 23:09
`/signin-oidc` is a default call back URL for the Microsoft Identity Platform. 

In Azure, your configuration should look like this

![image](https://user-images.githubusercontent.com/3304703/219211097-f738932a-f15e-4e51-a09e-269897c51a6a.png)

**Comment by saigkill** [comment] 2023-02-20 08:47
I have added the possible sites on AD:

<img width="754" alt="AD-URI" src="https://user-images.githubusercontent.com/75621/220055569-01827b65-d8ec-4b84-8ac1-5056a99e3248.png">

The app settings also using that url:

<img width="1433" alt="App-Settings" src="https://user-images.githubusercontent.com/75621/220055726-8d6d5fac-1f24-49a7-b8c5-68c5df2d0412.png">

What also confusing me is the message "The redirect URI 'http://mannsblog-stage.azurewebsites.net/signin-oidc' specified in the request does not match the redirect URIs configured for the application '0e8fb9fc-c20c-4464-8868-59f488583d2e'" This error comes by trying to login via button on https://mannsblog-stage.azurewebsites.net/signin-oidc.

**Comment by EdiWang** [comment] 2023-02-21 05:08
Are you using Docker with Linux app service plan or code deployment on Windows Plan?

**Comment by saigkill** [comment] 2023-02-21 17:48
Hi Edi. I'm using a Linux app plan with docker. AFAIK you too...
Maybe i have try to ask the AD Support.

**Comment by EdiWang** [comment] 2023-02-21 22:59
This may be a bug in Docker image for Moonglade. I'll investigate this issue. Meantime, if you still need Azure AD for login, you can create a new app service instance and redeploy the application from Visual Studio (publish menu). You can keep SQL database, storage account and settings. Otherwise, you can wait till I resolve this issue in Docker. 

I'll publish any update here during the investigation.

**Comment by EdiWang** [comment] 2023-02-22 06:04
Update: The problem is `https` was incorrectly written into `http` in Docker deployment. Investigating solution.

**Comment by EdiWang** [comment] 2023-02-22 06:29
Fixed in 64000531, will go to next release (v12.9.x)

**Comment by saigkill** [comment] 2023-02-22 11:09
Wow you rocks :-) I merged your last commits to my develop branch. Ill check it out 👍

**Comment by saigkill** [comment] 2023-02-22 18:44
Tested out. Works perfectly. Thanks.

**Closed** 2023-03-08 05:09 UTC
Labels: bug, pending release, area-admin, docker
