### ISSUE TITLE
Language selection not working properly

### ISSUE THREAD

**Issue by Lesliewxj** [EdiWang/Moonglade#487] opened 2020-09-23 11:26 UTC
**Describe the bug**
In the index,the chinese and english can not switch.

1. Go to 'lesliewxj.com'
2. Click on 'Language'
3. switch the Language

**Environment 
 - OS: Windows 10
 - Browser :Chrome
 - Version:70

**Comment by Lesliewxj** [comment] 2020-09-26 05:21
Everything is normal in the development environment and can switch between Chinese and English, but after deploying to the Alibaba Cloud server, the homepage cannot switch languages.

**Comment by EdiWang** [comment] 2020-09-26 10:17
Currently I'm not sure what is causing the issue, still investigating.

Environment | Can Reproduce
--- | ---
Production https://edi.wang with Azure Front Door and WAF | Yes
Staging https://staging.edi.wang without Azure Front Door and WAF | Yes
local IIS with release configuration | No
https://www.yycoding.xyz/, version 10.6.0 | No
https://blog.stackable.cn/, version 10.6.0 | No
https://zhuangkh.com/, version 10.6.0 | No
https://www.51azure.cloud/, version 10.6.0 | No
https://zchwei.com/, version 10.5.0 | No
https://anduin.aiursoft.com/, version 10.5.0 | No

**Comment by Lesliewxj** [comment] 2020-09-26 11:31
I changed the appsettings.json in "DefaultLangCode": "en-us" to "DefaultLangCode": "zh-cn" ,  but it seems do not work.

**Comment by EdiWang** [comment] 2020-10-05 07:46
The `DefaultLangCode` isn't for UI language, it is for the HTML5 language attribute for blog posts, and this setting has been moved to admin portal in the next release. 

I am still investigating the issue. Currently it only happens to your deployment and my own. Regardless of using Azure App Service or VM, it seems to be related to somewhere in the host machine configuration.

I will post an update when I have some clue.

**Comment by EdiWang** [comment] 2020-10-05 08:26
The impacted deployments are missing `zh-CN` folder and `Moonglade.Web.resources.dll`. After uploading them manually to my staging server, the language selector works.

![image](https://user-images.githubusercontent.com/3304703/95056206-f544a380-0726-11eb-99fc-cd7c21eff54e.png)

![image](https://user-images.githubusercontent.com/3304703/95056328-24f3ab80-0727-11eb-838b-9c6cc92ddfe1.png)

This issue may be caused by incorrect build process. I am still investigating and will follow up this thread.

**Comment by EdiWang** [comment] 2020-10-05 08:45
By switching to Windows build agent (https://github.com/EdiWang/Moonglade/commit/af8de564793fa5ba0b95b11192de9359606dae8d), the output artifact is containing zh-CN resource file correctly. Seems problem with .NET Core SDK on Linux. 

@Lesliewxj you may try to change your build machine to Windows and see if it works for you.

**Comment by Lesliewxj** [comment] 2020-10-05 10:50
My blog data cannot be exported. I will use this version first, and I will look at it after the problem is fixed. thank you very much

**Comment by EdiWang** [comment] 2020-10-06 02:55
For data exporting, please submit another issue.

Per this thread, there's nothing I can do to. The language localization is due to incorrect build process for the .NET Core SDK on Linux, it needs to be fixed by Microsoft, not me. 

The workaround is to use Windows machine as your build environment, not Linux.

**Closed** 2020-10-06 02:59 UTC
Labels: 3rd-party-issue, area-settings, bug, localization, wontfix, workaround

**Comment by Lesliewxj** [comment] 2020-10-07 05:56
OK,thanks a lot.
