### ISSUE TITLE
Support changing the avatar background image

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#305] opened 2019-12-07 09:54 UTC
![image](https://user-images.githubusercontent.com/19531547/70372482-876af800-191a-11ea-9a49-aec921ed2036.png)

My background is ugly. How can I change it without changing my icon?

**Comment by EdiWang** [comment] 2019-12-12 01:33
This is by design. It blurs the background with your avatar image. Close this issue violently and ignore @Anduin2017

**Closed** 2019-12-12 01:33 UTC
Labels: UI, wontfix
